environment:
  matrix:
    - nodejs_version: 10
os: Visual Studio 2015

platform:
  - x64

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy:
  description: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: vnkvX42UeMmuBusEVcqjxmIsxuH8fQ0rJTbKo5OuRzaNeZuUJ99IeUSBSTev1SL7
  artifact: /\/build\/stage\/.*\.gz/            # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
    #branch: feature/app-veyor-github                 # release from master branch only