environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10
    - nodejs_version: 11
    - nodejs_version: 12
    # electron
    - nodejs_version: 12
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 6.0.2
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 12
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 5.0.9
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 4.2.8
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron        
    - nodejs_version: 10
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 4.1.5
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 4.0.8
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron      
    - nodejs_version: 10
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 3.0.9
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 8
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 2.0.7
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
      MOCHA_RUNTIME_VERSION: 7.0.0
    - nodejs_version: 8
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 1.8.7
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
      MOCHA_RUNTIME_VERSION: 7.0.0
os: Visual Studio 2015

platform:
  - x64
  - x86

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy:
  description: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: vnkvX42UeMmuBusEVcqjxmIsxuH8fQ0rJTbKo5OuRzaNeZuUJ99IeUSBSTev1SL7
  artifact: build/stage/.*\.gz/            # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
    #branch: master                 # release from master branch only
